version: '3'
services:

  redis:
    image: redis:4.0.5-alpine
    hostname: redis
    ports:
    - 6380:6379

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
    - 27018:27017

## uncomment it to initialize data
#  mongo-seed:
#    build: ./mongo-seed
#    links:
#    - mongodb